digicatapult/sqnc-node

Cargo.lock
README.md
node/Cargo.toml
node/src/chain_spec.rs
runtime/Cargo.toml
runtime/src/lib.rs

We want to limit which nodes connect to other nodes on the chain to stop unknown nodes from accessing the chain and reading chain data. Substrate provide the node-authorization pallet for creating and managing a permissioned network of nodes.
The file changes cover the following steps:
```
dev
- Alice
staging
- stage (red/green/blue/bootnode)
- stage2 (red/green/blue)
- stage3 (red/green/blue)
local
- Alice
- Bob
- Charlie 
- Eve
```
The process for adding genesis config to a live chain (in this case adding an initial set of permissioned well-known nodes) is documented [here](https://digicatapult.atlassian.net/wiki/spaces/EN/pages/1736015886/Adding+genesis+config+to+a+live+chain).
The process for adding a new node, either as a well-known node or a sub-node, to an already permissioned …

VIT-115 Limit node connections and access to chain data

---

README.md

Adds the PeerId type (for [node-authorization](https://docs.rs/pallet-node-authorization/3.0.0/pallet_node_authorization/index.html)) to the list of additional types needed when using `polkadot.js`.

Add PeerId type for node-authorization

---

Cargo.lock
README.md
node/Cargo.toml
pallets/simple-nft/src/benchmarking.rs
pallets/simple-nft/src/lib.rs
pallets/simple-nft/src/mock.rs
pallets/simple-nft/src/tests.rs
pallets/simple-nft/src/weights.rs
runtime/src/lib.rs

Represent multiple roles on a token beyond `owner` so we can more easily understand which accounts it's allowable to transfer a token to. In the future this will allow multiple parties to make the next statement on an asset (token) without having to transact back and forth.
`owner: AccountId` -> `roles: BTreeMap<RoleKey, AccountId>`
At runtime, `RoleKey` has type of `Role` which represents an enumeration of the sensible roles (agreed with Luca) we anticipate for the project.
```
pub enum Role {
Admin, //Default
ManufacturingEngineer,
ProcurementBuyer,
ProcurementPlanner,
Supplier,
}
```
For now, `run_process` checks that the sender `AccountId` matches the `AccountId` for the default role (`Admin`) of all `input` tokens, more nuance will be added to this in the future.

Multiple token roles

---

Cargo.lock
README.md
node/Cargo.toml
pallets/simple-nft/Cargo.toml
pallets/simple-nft/src/mock.rs
pallets/simple-nft/src/tests.rs
runtime/Cargo.toml
runtime/src/lib.rs

Makes it possible for metadata to be of the existing `TokenId` type.

Add TokenId to MetadataValue

---

.github/workflows/release.yml
Cargo.lock
Dockerfile
node/Cargo.toml

A new docker file that builds and image using pre-compiled binaries.
Our docker builds are very slow, so we are considering a replacement with a simpler build that downloads pre-compiled artefacts.
- ☑️ Docker build time and rust compilation optimisations
- ☑️ Caching for rust compilation
```
▶ docker run -it --rm vitalam-node:minideb          11:30:31
2022-01-12 11:30:36 VITALam Node    
2022-01-12 11:30:36 ✌️  version 2.5.1-7b7d8d4-x86_64-linux-gnu    
2022-01-12 11:30:36 ❤️  by Digital Catapult <https://www.digicatapult.org.uk>, 2020-2022    
2022-01-12 11:30:36 📋 Chain specification: VITALam    
2022-01-12 11:30:36 🏷 Node name: gifted-earth-7985    
2022-01-12 11:30:36 👤 Role: FULL    
2022-01-12 11:30:36 💾 Database: RocksDb at /root/.local/share/vitalam-node/chains/vitalam/db …
```

Create minideb docker image

---

.github/workflows/check-and-test.yml
.github/workflows/release.yml
scripts/check-version.sh

Add pre-release versioning for feature branches

Pre release workflow

---

.github/release.yml
.github/workflows/release.yml
CONTRIBUTING.md
Cargo.lock
node/Cargo.toml

Uses the new [automatic release notes](https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes) GitHub feature to generate release notes, aka `changelog`, based on PR labels. 
Example auto-generated release notes:

Automatically generated release notes

---

.github/workflows/release.yml

**Problem**
The vitalam version needs to be passed as a build arg to the docker image compilation, otherwise the build can't specify the tag to download assets from.
**Solution**
Set the build-arg so that the vitalam version is set when compiling the dockerfile

Set the vitalam version build arg

---

Cargo.lock
README.md
node/Cargo.toml
pallets/simple-nft/src/mock.rs
pallets/simple-nft/src/tests.rs
runtime/Cargo.toml
runtime/src/lib.rs

Change the node roles enum to include all the roles we expect to use in our VITALam + INTELI demos. Default role `Admin` -> `Owner`
Roles:
`["Owner", "Customer", "AdditiveManufacturer", "Laboratory", "Buyer", "Supplier", "Reviewer"]`

Use demo roles

---

.github/workflows/release.yml
Cargo.lock
node/Cargo.toml

Uses [github-script](https://github.com/actions/github-script) to delete `tags/latest` so we get a new `latest` release that matches our most recent release.

Replace rather than update latest release

---

Cargo.lock
README.md
node/Cargo.toml
pallets/process-validation/Cargo.toml
pallets/process-validation/src/benchmarking.rs
pallets/process-validation/src/lib.rs
pallets/process-validation/src/restrictions.rs
pallets/process-validation/src/tests.rs
pallets/process-validation/src/tests/create_process.rs
pallets/process-validation/src/tests/disable_process.rs
pallets/process-validation/src/weights.rs
pallets/simple-nft/Cargo.toml
pallets/simple-nft/src/lib.rs
pallets/simple-nft/src/tests.rs
pallets/traits/Cargo.toml
pallets/traits/src/lib.rs
runtime/Cargo.toml
runtime/src/lib.rs

This PR lays the foundations for the process validation storage and evaluation pallet. There's no real functionality yet but what I have done is:
* created a new pallet `pallet-process-validation` which will store and manage the creation/disabling of process restrictions
* loosely coupled the new pallet to `pallet-simple-nft` via a shared trait and a struct that can describe a process input or output `ProcessIO`
* boiler plate for tests, benchmarking, weights
~I don't believe that this change will change any of the types used by the API~ Types still need updating

First stab at the process validation pallet

---

Cargo.lock
node/Cargo.toml
pallets/simple-nft/Cargo.toml
pallets/simple-nft/src/lib.rs
pallets/simple-nft/src/tests.rs
pallets/simple-nft/src/weights.rs
runtime/Cargo.toml

When multiple tokens are about the same thing e.g a PO, we want them all to have the same `original_id`. This PR changes the pallet to correctly assign `original_id` rather than the `id` of a parent to a new token's `original_id`.
e.g. assuming all these tokens are about the same thing, such as a `Quote`. This PR goes from this:
Token 1: `id: 1` `original_id: 1`
Token 2: `id: 2` `original_id: 1`
Token 3: `id: 3` `original_id: 2` // this is wrong
to this
Token 1: `id: 1` `original_id: 1`
Token 2: `id: 2` `original_id: 1`
Token 3: `id: 3` `original_id: 1` // this is correct

Bug/Use original_id of parent for new token original_id

---

helm/vitalam-node/Chart.yaml
helm/vitalam-node/templates/service.yaml
helm/vitalam-node/templates/statefulset.yaml

Changes long service names to something shorter
When using this chart as a subchart we prepend the `releasename` with the parent charts name.  As such we get serviceNames that are too long.
```Error: INSTALLATION FAILED: Service "vitalam-identity-service-zuvp6takjp-vitalamnode-0-relay-chain-p2p" is invalid: metadata.name: Invalid value: "vitalam-identity-service-zuvp6takjp-vitalamnode-0-relay-chain-p2p": must be no more than 63 characters```

Altered service names so they are shorter

---

helm/vitalam-node/Chart.yaml
helm/vitalam-node/templates/_helpers.tpl
helm/vitalam-node/templates/service.yaml
helm/vitalam-node/templates/statefulset.yaml
helm/vitalam-node/values.yaml

Adds ability to use different service types `ClusterIP` and `LoadBalancer`
Logic to determine if to use a public addr
Fixes some bugs in the parity chart with regards to bash flow logic on Parachain section
Parachain functionality needs to be tested against `Polkadot` container in the coming week.

Adds types LoadBalancer and ClusterIP to valid service types

---

helm/vitalam-node/Chart.yaml
helm/vitalam-node/templates/customNodeKeySecret.yaml
helm/vitalam-node/templates/statefulset.yaml

Fixed a bug whereby you couldn't use a custom node key on more than a singe helm release per namespace

bug/custom-node-key non-unique

---

Cargo.lock
README.md
node/Cargo.toml
pallets/process-validation/Cargo.toml
pallets/process-validation/src/lib.rs
pallets/process-validation/src/restrictions.rs
runtime/Cargo.toml
runtime/src/lib.rs

Uses an input value for the index as well as a TokenValueData and TokenValueKey to get the correct values. This has 2 tests and has been tested on Polkadot.

IN-101 Restrict Metadata value to be a fixed value

---

Cargo.lock
node/Cargo.toml
pallets/process-validation/Cargo.toml
pallets/process-validation/src/lib.rs
pallets/process-validation/src/tests/disable_process.rs
runtime/Cargo.toml
runtime/src/lib.rs

1. bring up a local developer chain
2. create a process with some `id` for example `0x7465737400000000000000000000000000000000000000000000000000000000`. It doesn’t matter what restrictions are used. Ensure this is created with `version` `1`
3. create another process with the same `id`. Ensure this is created with `version` `2`
4. disable the process with the matching `id` and `version` `1`
5. Get the process for the `id` and `version` `1` from the `processModel`
The process to have a `state` of `Disabled`
The process has a state of `Enabled`

Fix bug which prevented the disabling of previous process versions

---

Cargo.lock
README.md
node/Cargo.toml
pallets/process-validation/Cargo.toml
pallets/process-validation/src/restrictions.rs
pallets/simple-nft/src/tests.rs
runtime/Cargo.toml
runtime/src/lib.rs

Allow restriction on the value of a metadata item for an **output** at a specific index in the output `Vec`. This restriction is limited to a pre-specified value and cannot depend on other inputs or outputs.
In polkadot apps:

Restrict a metadata value for an output to a fixed value

---

Cargo.lock
README.md
api/lib/api.js
api/package-lock.json
api/package.json
node/Cargo.toml
pallets/process-validation/Cargo.toml
pallets/process-validation/src/restrictions.rs
runtime/Cargo.toml
runtime/src/lib.rs

Allow restriction on the identity of a named role on an output to the sender of a run_process transaction

Restrict role a transaction executor must have on an output

---

Cargo.lock
Dockerfile
README.md
api/lib/api.js
api/package-lock.json
api/package.json
helm/dscp-node/Chart.yaml
node/Cargo.toml
pallets/process-validation/Cargo.toml
pallets/process-validation/src/lib.rs
pallets/process-validation/src/restrictions.rs
pallets/process-validation/src/tests.rs
runtime/Cargo.toml
runtime/src/lib.rs

Allows restricting the type of a metadata value for a specific output key on a specific output index

Restrict output metadata value type

---

Cargo.lock
README.md
api/lib/api.js
api/package-lock.json
api/package.json
helm/dscp-node/Chart.yaml
node/Cargo.toml
pallets/process-validation/Cargo.toml
pallets/process-validation/src/lib.rs
pallets/process-validation/src/restrictions.rs
pallets/process-validation/src/tests.rs
pallets/process-validation/src/tests/create_process.rs
runtime/Cargo.toml
runtime/src/lib.rs

Boolean logic (AND/OR/XOR/NOR/NAND) for restrictions so you can logically combine different restrictions together.

Add boolean binary restriction

---

Cargo.lock
node/Cargo.toml
pallets/doas/Cargo.toml
pallets/doas/src/lib.rs
pallets/doas/src/mock.rs
pallets/doas/src/tests.rs
pallets/process-validation/Cargo.toml
pallets/simple-nft/Cargo.toml
pallets/symmetric-key/Cargo.toml
pallets/symmetric-key/src/lib.rs
pallets/symmetric-key/src/tests.rs
pallets/symmetric-key/src/tests/rotate_key.rs
pallets/symmetric-key/src/tests/schedule.rs
pallets/symmetric-key/src/tests/update_key.rs
pallets/traits/Cargo.toml
runtime/Cargo.toml

This PR upgrades our substrate install from `v3.0.0` to `polkadot-0.9.25` which is the latest polkadot branch. A few notes:
* I have to upgrade all the `Cargo.toml` files in lockstep as otherwise cargo is unhappy. Hence why everything has changed
* The big changes are that all externally facing types must implement `TypeInfo` and `MaxEncodedLen`. This means moving away from unbound types like `Vec` in externally facing type signatures.
* Tests will fail on other pallets until this is all upgraded, but the two pallets modified now all pass locally
* Further work will be required to integrate with polkadot-js

Feature/upgrade substrate - pallet-doas and pallet-symetric-key

---

Cargo.lock
node/Cargo.toml
node/src/chain_spec.rs
node/src/cli.rs
node/src/command.rs
node/src/command_helper.rs
node/src/main.rs
node/src/rpc.rs
node/src/service.rs
pallets/doas/Cargo.toml
pallets/process-validation/Cargo.toml
pallets/process-validation/src/lib.rs
pallets/simple-nft/Cargo.toml
pallets/symmetric-key/Cargo.toml
runtime/Cargo.toml
runtime/src/lib.rs

Upgrades the `dscp-node` and `dscp-node-runtime` to `polkadot-0.9.25` version of substrate. Many of the changes here are taken from https://github.com/substrate-developer-hub/substrate-node-template repository and how the client has been upgraded there

Upgrade dscp node

---

Cargo.lock
api/package-lock.json
api/package.json
helm/dscp-node/Chart.yaml
node/Cargo.toml
runtime/Cargo.toml
runtime/src/lib.rs

Increases the maximum allowed metadata count on a token from `16` to `64`

Increase max metadata count to 64

---

Cargo.lock
README.md
api/package-lock.json
api/package.json
node/Cargo.toml
pallets/process-validation/Cargo.toml
pallets/process-validation/src/binary_expression_tree.rs
pallets/process-validation/src/lib.rs
pallets/process-validation/src/restrictions.rs
pallets/process-validation/src/tests.rs
pallets/process-validation/src/tests/create_process.rs
pallets/process-validation/src/tests/disable_process.rs
pallets/process-validation/src/tests/validate_process.rs
runtime/Cargo.toml
runtime/src/lib.rs

Re-enables the functionality that used to be encoded in the Combined restriction type. To avoid circular type references and to simplify the API this has instead been achieved by abstracting out the way restricitons are combined. Previously top-level we assumed that restrictions should be 'AND'ed together. Now an arbitrary binary expression tree is used  written in postfix notation.
Also added are a Fail restriction type which always fails to pass. This is useful both for testing and for doing certain unary operations as the tree only excepts binary operations.
There is some opinionation as to what the defaul should be for the Process program. This change maintains current behaviour that the program will always succeed.

Re-enable combined restriction functionality

---

Cargo.lock
api/package-lock.json
api/package.json
node/Cargo.toml
node/src/rpc.rs
runtime/Cargo.toml
runtime/src/lib.rs

Re-implementes the transaction payment which the polkadot UI in places requires. Note the APIs return the fee as zero but this allows propoals to be enacted by the UI once again.

Fix proposal close functionality

---

.github/workflows/check-and-test.yml
.github/workflows/release-helm.yml
.github/workflows/release-types-package.yml
.github/workflows/release.yml
.github/workflows/test-types.yml
.github/workflows/types-package.yml
api/package-lock.json
api/package.json
helm/dscp-node/Chart.yaml
node/Cargo.toml
runtime/Cargo.toml
runtime/src/lib.rs
scripts/check-helm-version.sh
scripts/check-package-version.sh
scripts/check-version.sh

See reduced number of annotations https://github.com/digicatapult/dscp-node/actions/runs/3321131708. 
`rustup` and `cargo` actions still use node 12 for now [ticket](https://digicatapult.atlassian.net/browse/IN-401)
Explanation for remaining warnings https://github.com/digicatapult/dscp-api/pull/60

Update deprecated actions

---

Cargo.lock
api/package-lock.json
api/package.json
helm/dscp-node/Chart.yaml
node/Cargo.toml
pallets/process-validation/src/benchmarking.rs
pallets/process-validation/src/binary_expression_tree.rs
pallets/process-validation/src/lib.rs
pallets/process-validation/src/restrictions.rs
pallets/process-validation/src/weights.rs
pallets/simple-nft/src/benchmarking.rs
runtime/Cargo.toml
runtime/src/lib.rs

Benchmarks for:
1. `create_process`
- iterate over number of program input
- maximum length is ~~200~~ 201 of restrictions + boolean ops (length is always odd)
2. `disable_process`
Weights generated and attatched to extrinsics

Add benchmarks and weights for pallet-process-validation

---

.github/workflows/release.yml
api/package-lock.json
api/package.json
helm/dscp-node/Chart.yaml
node/Cargo.toml
runtime/Cargo.toml
runtime/src/lib.rs
scripts/check-version.sh

Fix a mistake in #92 that's causing prerelease builds to be set as `latest` rather than `prerelease`

Stop prerelease builds being tagged as latest

---

README.md
Upgrade.md

This follow the process that was used upgrading Polkadot 0.9.25 to 0.9.30. It also links to other repos which contain other useful information. 
It also references [diener](https://crates.io/crates/diener), a crate which makes changing Substrate and Polkadot version easier.

Upgrade Substrate Document

---

Cargo.lock
api/package-lock.json
api/package.json
helm/dscp-node/Chart.yaml
node/Cargo.toml
node/src/cli.rs
pallets/doas/Cargo.toml
pallets/process-validation/Cargo.toml
pallets/simple-nft/Cargo.toml
pallets/symmetric-key/Cargo.toml
pallets/symmetric-key/src/lib.rs
pallets/symmetric-key/src/tests.rs
pallets/symmetric-key/src/tests/schedule.rs
pallets/traits/Cargo.toml
pallets/transaction-payment-free/Cargo.toml
pallets/transaction-payment-free/src/mock.rs
pallets/transaction-payment-free/src/tests.rs
runtime/Cargo.toml
runtime/src/lib.rs

This PR upgrades Polkadot to version 0.9.32. Where necessary changes have been made to the code in order to meet the new spec. For example, using `Weight::zero()` instead of `Weight::from_ref_time(0)`.

Upgrade Polkadot to Version 0.9.32

---

Cargo.lock
api/package-lock.json
api/package.json
helm/dscp-node/Chart.yaml
node/Cargo.toml
pallets/symmetric-key/Cargo.toml
pallets/symmetric-key/src/lib.rs
pallets/symmetric-key/src/tests.rs
pallets/symmetric-key/src/tests/rotate_key.rs
pallets/symmetric-key/src/tests/schedule.rs
pallets/symmetric-key/src/tests/update_key.rs
runtime/Cargo.toml
runtime/src/lib.rs

The current test logic on `pallet-symmetric-key`'s `schedule` tests is a bit flawed. The intension is to assert that the schedule indeed runs automatically on an interval but the tests don’t actually do this. Instead what’s happening is the schedule is initialised once (and this is tested), but the following interval is not. This ticket will look to improve the tests by
- making explicit that the existing test is only testing the schedule initialisation
- adding another test to assert that the schedule indeed fires on an interval
To achieve the latter case I had to implement our own `TestRandomness` as the one in substrate doesn’t actually change.

Improve schedule tests on symmetric key

---

renovate.json

Updating `jsonrpsee` is causing our renovate auto-update to fail https://github.com/digicatapult/dscp-node/pull/123

Ignore `jsonrpsee` for Renovate

---

README.md

---
name: Bug report
about: Create a report to help us improve
---
- Checked the FAQs for common solutions: <https://github.com/digicatapult/dscp-node/blob/main/CONTRIBUTING.md/#FAQs>
- Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Adscp-node>
Repository named `dscp`, README makes reference to `veritable`
1. 
2. 
3. 
**Expected behaviour:**
README refers to `dscp`
**Actual behaviour:**
README refers to `veritable` in places
**Reproduces how often:**

Replace uses of `veritable` with `dscp` and add a little more context to the introductory sentence

---

Cargo.lock
node/Cargo.toml
runtime/Cargo.toml
runtime/src/lib.rs

In #146 we forgot to bump the runtime and node version. Bump

Bump node and runtime versions

---

Cargo.lock
tools/lang/Cargo.toml
tools/lang/src/compiler/condition_transform.rs

Removes an assertion on `TokenToken` (e.g. `token_a == token_b`) equality checks that the two tokens are the same type. This is not a requirement in all use cases

Allow equality between different token types

---

Cargo.lock
node/Cargo.toml
node/src/cli.rs
node/src/command.rs
tools/lang/Cargo.toml
tools/lang/src/cli.rs
tools/lang/src/convert.rs
tools/lang/src/errors.rs
tools/lang/src/lib.rs
tools/lang/src/main.rs

Adds dscp-lang as a subcommand of dscp-node under lang. This involved a number of changes:
- made `dscp-lang` both a lib and a bin
- update `dscp-node` to include `lang` subcommand
- update exports from dscp-lang to have necessary visibility and trait impls
In addition this includes:
- update output from `lang build` command when passing `-v` to actually be verbose and more useful

Integrate dscp-lang into dscp-node

---

.github/workflows/release.yml
Cargo.lock
node/Cargo.toml
node/src/cli.rs
node/src/command.rs
node/src/main.rs
node/src/rpc.rs
node/src/test_service.rs
runtime/Cargo.toml
runtime/src/lib.rs

When running integration tests on repositories that depend on `dscp-node` we have to limit tests that interact with the chain because of the 6s block generation time. This PR enables a `--manual_seal` option when running with `--dev` that will allow us to manually trigger block generation and finalisation usng an RPC command. This should make it much more practical for us to have an extensive suite of integration tests.

Add option to enable manual sealing of blocks when in dev mode

---

Cargo.lock
Cargo.toml
node/Cargo.toml
pallets/doas/Cargo.toml
pallets/process-validation/Cargo.toml
pallets/process-validation/src/binary_expression_tree.rs
pallets/process-validation/src/lib.rs
pallets/process-validation/src/restrictions.rs
pallets/process-validation/src/tests.rs
pallets/symmetric-key/Cargo.toml
pallets/symmetric-key/src/tests.rs
pallets/traits/Cargo.toml
pallets/traits/src/lib.rs
pallets/transaction-payment-free/Cargo.toml
pallets/transaction-payment-free/src/lib.rs
pallets/transaction-payment-free/src/payment.rs
pallets/utxo-nft/Cargo.toml
pallets/utxo-nft/src/graveyard.rs
pallets/utxo-nft/src/lib.rs
pallets/utxo-nft/src/output.rs
pallets/utxo-nft/src/tests/mock.rs
pallets/utxo-nft/src/token.rs
runtime/Cargo.toml
runtime/src/lib.rs
runtime/types/Cargo.toml
runtime/types/src/lib.rs
tools/lang/Cargo.toml

Re-organises our dpeendencies into the workspace `Cargo.toml` so that we can refer to consistent versions everywhere. This should make it easier for us to upgrade dependencies (especially substrate deps) in the future. 
Note this doesn't upgrade any dependencies or change nay code other than some package renames. Hence no benchmark updates

Reorganise deps into workspace

---

Cargo.lock
Dockerfile
node/Cargo.toml
runtime/Cargo.toml

Adds a healthcheck to the Dockerfile so that we can orchestrate the order in which services start in our docker compose files

Add healthcheck to Dockerfile

---

README.md

Match the process flow diagram in the `README.md` to the text description

Match diagram to description

---

Cargo.lock
node/Cargo.toml
runtime/Cargo.toml
runtime/src/lib.rs
runtime/types/Cargo.toml
runtime/types/src/lib.rs
tools/lang/Cargo.toml
tools/lang/src/ast/parse.rs
tools/lang/src/ast/types.rs
tools/lang/src/compiler/condition_transform.rs
tools/lang/src/compiler/flatten.rs
tools/lang/src/compiler/token_transform.rs
tools/lang/src/sqnc.pest

Adds integer types to metadata in the runtime.
This also adds support for integers and integer literals to the language.
Integer values still only support equals and not equals comparisons for now. Baby steps
Documentation PR https://github.com/digicatapult/sqnc-documentation/pull/33

feat: Add integer types to metadata

---

Cargo.lock
Cargo.toml
Upgrade.md
node/Cargo.toml
pallets/doas/Cargo.toml
pallets/process-validation/Cargo.toml
pallets/symmetric-key/Cargo.toml
pallets/traits/Cargo.toml
pallets/transaction-payment-free/Cargo.toml
pallets/utxo-nft/Cargo.toml
runtime/Cargo.toml
runtime/src/lib.rs
runtime/types/Cargo.toml
scripts/check-version.sh
tools/lang/Cargo.toml

Please delete options that are irrelevant.
SQNC-73
Introduced new versioning strategy agreed in SQNC-41.
The agreed new strategy uses a single version set in the `Cargo.toml` at root level. this is then used by all the other `Cargo.toml`s. 
We are from now on also incrementing `spec_version` by one e.g 1131 -> 1132 as part of a version bump. 
Made a line change in `check-version.sh` to obtain current version from the root `Cargo.toml` instead of one in node. 
As per SQNC-41, we have considered per-crate versioning strategy and a hybrid versioning approach. We have decided to proceed with Unified versioning as the crates are tightly coupled.

new versioning strategy
